export const INCREMENTED = 'INCREMENTED'
export const DECREMENTED = 'DECREMENTED'

export const GET_PRODUCT = "GET_PRODUCT"
export const POST_PRODUCT = "POST_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const LOADING_MEDICINE = "LOADING_MEDICINE"
export const ERROR_MEDICINE = "ERROR_MEDICINE"

export const GET_DOCTOR = "GET_DOCTOR"
export const POST_DOCTOR = "POST_DOCTOR"
export const DELETE_DOCTOR = "DELETE_DOCTOR"
export const UPDATE_DOCTOR = "UPDATE_DOCTOR"
export const LOADING_DOCTOR = "LOADING_DOCTOR"
export const ERROR_DOCTOR = "ERROR_DOCTOR"

export const CART_ADD_DATA = "CART_ADD_DATA"
export const CART_GET_DATA = "CART_GET_DATA"
export const CART_DELETE_DATA = "CART_DELETE_DATA"

export const LOADING_MEDICINES = "LOADING_MEDICINES"
export const ERROR_MEDICINES = "ERROR_MEDICINES"

export const GET_ORDER = "GET_ORDER"
export const POST_ORDER = "POST_ORDER"