export const INCREMENTED = 'INCREMENTED'
export const DECREMENTED = 'DECREMENTED'

export const GET_MEDICINE = "GET_MEDICINE"
export const POST_MEDICINE = "POST_MEDICINE"
export const DELETE_MEDICINE = "DELETE_MEDICINE"
export const UPDATE_MEDICINE = "UPDATE_MEDICINE"
export const LOADING_MEDICINE = "LOADING_MEDICINE"
export const ERROR_MEDICINE = "ERROR_MEDICINE"

export const GET_DOCTOR = "GET_DOCTOR"
export const POST_DOCTOR = "POST_DOCTOR"
export const DELETE_DOCTOR = "DELETE_DOCTOR"
export const UPDATE_DOCTOR = "UPDATE_DOCTOR"
export const LOADING_DOCTOR = "LOADING_DOCTOR"
export const ERROR_DOCTOR = "ERROR_DOCTOR"